package lio;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JOptionPane;
import cons.Cons;

/**
 * リスト表現を用いた入出力「ペン←→二進木(リスト表現)←→ファイル」の例題プログラム。
 */
public class Example extends Object
{
	/**
	 * ペンを二進木に変換してリスト表現としてファイルに保存する例題プログラム。
	 * 逆にファイルに保存されたリスト表現を読み込んでペンを作る例題プログラム。
	 */
	public static void main(String[] arguments)
	{
		// ペンのオブジェクトを作る。
		Pen aPen = new Pen();
		aPen.position(100, 200);
		aPen.color(Color.orange);
		aPen.nib(3);

		// ペンのオブジェクトを書き込む。
		aPen = Example.write(aPen);
		if (aPen == null) { return; }

		String aString = "Writing was finished:\n" + aPen.toString();
		System.out.println(aString);
		JOptionPane.showMessageDialog(null, aString, "Notify", JOptionPane.PLAIN_MESSAGE);

		// ペンのオブジェクトを読み込む。
		aPen = Example.read();
		if (aPen == null) { return; }

		aString = "Reading was finished:\n" + aPen.toString();
		System.out.println(aString);
		JOptionPane.showMessageDialog(null, aString, "Notify", JOptionPane.PLAIN_MESSAGE);
		
		return;
	}
	
	/**
	 * ペンのオブジェクトをファイルに書き込む。
	 */
	public static Pen write(Pen aPen)
	{
		// ファイル名として用いる日時の文字列を作る。
		Date aDate = new Date();
		SimpleDateFormat aFormat = new SimpleDateFormat("yyyyMMddHHmmss");
		String aString = aFormat.format(aDate);
		
		// 書き込むためのファイルを選択する。
		JFileChooser fileChooser = new JFileChooser();
		FileFilter fileFilter = new FileNameExtensionFilter("Pen (*.penText)", "penText");
		fileChooser.addChoosableFileFilter(fileFilter);
		fileChooser.setSelectedFile(new File(aString + ".penText"));
		int answer = fileChooser.showSaveDialog(null);
		if (answer != JFileChooser.APPROVE_OPTION) { return null; }
		File aFile = fileChooser.getSelectedFile();
		
		// 書き込むファイルがすでに存在している場合に上書きしてもいいかを問い合わせる。
		if (aFile.exists())
		{
			aString = "Really overwrite?";
			answer = JOptionPane.showConfirmDialog(null, aString, "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
			if (answer == JOptionPane.NO_OPTION) { return null; }
		}
		
		// ペンのオブジェクトを二進木に変換する。
		Cons aList = aPen.toList();
		
		// その二進木をプリティプリントされたリスト表現文字列に変換して、ヘッダとフッタを付けて、ファイルに書き込む。
		aString = aList.ppString();
		try
		{
			OutputStreamWriter aStream = new OutputStreamWriter(new FileOutputStream(aFile), "UTF-8");
			aStream.write("# This file was generated by Pen at ");
			aStream.write(((new SimpleDateFormat("yyyy/MM/dd HH:mm:ss.")).format(new Date())));
			aStream.write("\n\n");
			aStream.write(aString);
			aStream.write("\n\n");
			aStream.write("# Pen has been released by AOKI Atsushi in January 15, 2011.\n");
			aStream.close();
 		}
		catch (IOException anException)
		{
			throw new RuntimeException(anException.toString());
		}
		
		return aPen;
	}

	/**
	 * ペンのオブジェクトをファイルから読み込んで応答する。
	 */
	public static Pen read()
	{
		// 読み込むためのファイルを選択する。
		JFileChooser fileChooser = new JFileChooser();
		FileFilter fileFilter = new FileNameExtensionFilter("Pen (*.penText)", "penText");
		fileChooser.addChoosableFileFilter(fileFilter);
		int answer = fileChooser.showOpenDialog(null);
		if (answer != JFileChooser.APPROVE_OPTION) return null;
		File aFile = fileChooser.getSelectedFile();
		
		// プリティプリントされたリスト表現文字列を読み込む。
		StringBuffer aBuffer = new StringBuffer();
		try
		{
			InputStreamReader aStream = new InputStreamReader(new FileInputStream(aFile), "UTF-8");
			int aCharacter;
			while ((aCharacter = aStream.read()) != -1)
			{
				aBuffer.append((char)aCharacter);
			}
			aStream.close();
 		}
		catch (IOException anException)
		{
			throw new RuntimeException(anException.toString());
		}
		String aString = aBuffer.toString();
		
		// リスト表現文字列をパーズして二進木を作り上げる。
		Cons aList = (Cons)Cons.parse(aString);
		
		// 二進木からペンのオブジェクト作り上げて応答する。
		Pen aPen = new Pen(aList);
		return aPen;
	}
}
